<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>vso</string>
   </array>
  <key>name</key>
  <string>vso</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.vso</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#multi_line_comment</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((\#\+){1}(.*))</string>
          <key>name</key>
          <string>comment.vso</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\*{3})</string>
          <key>name</key>
          <string>keyword.operator.vso</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\*{2})</string>
          <key>name</key>
          <string>keyword.other.vso</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\*{1})</string>
          <key>name</key>
          <string>markup.heading.vso</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([\x{2299}])</string>
          <key>name</key>
         <string>markup.heading.vso</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([\x{2298}])</string>
          <key>name</key>
          <string>keyword.other.vso</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([\x{2296}])</string>
          <key>name</key>
          <string>keyword.operator.vso</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([\x{229A}])</string>
          <key>name</key>
         <string>entity.name.type.vso</string>
        </dict>
        
        <dict>
          <key>match</key>
          <string>([\x{229A}])</string>
          <key>name</key>
          <string>entity.name.tag.vso</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\bTODO\b)</string>
          <key>name</key>
          <string>invalid.illegal.vso</string>
        </dict>
      <dict>
          <key>match</key>
          <string>((\bDONE\b))</string>
          <key>name</key>
          <string>entity.name.function.vso</string>
        </dict>  
     

       </array>
    </dict>
    <key>multi_line_comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(/\*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.vso</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.vso</string>
          <key>end</key>
          <string>(\*/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>numeric.vso</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b\d+)</string>
          <key>name</key>
          <string>constant.numeric.vso</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
