<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <array>
            <string>vso</string>
            <string>vsorg</string>
        </array>
   </array>
  <key>name</key>
  <string>vsorg</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.vso</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        
        <dict>
          <key>include</key>
          <string>#h1</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.vso</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.vso</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#multi_line_comment</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(//.*)</string>
          <key>name</key>
          <string>comment.vso</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>text.vso</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(.[\x{002a}]{3}(.*))</string>
          <key>name</key>
          <string>keyword.vso</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(.[\x{002a}]{2}(.*))</string>
          <key>name</key>
          <string>entity.name.function.vso</string>
        </dict>
       <dict>
          <key>match</key>
          <string>(.[\x{002a}]{1}(.*))</string>
          <key>name</key>
          <string>punctuation.mysample</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(.[\x{24b8}]{1}(.*))</string>
          <key>name</key>
          <string>entity.name.function.vso</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(/\*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.vso</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.vso</string>
          <key>end</key>
          <string>(\*/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.vso</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b\d+)</string>
          <key>name</key>
          <string>constant.numeric.vso</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
